[phases.setup]
nixPkgs = ["python311", "python311.pkgs.pip"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --worker-class gthread --workers=2 --bind 0.0.0.0:$PORT"
